version: '3.8'

services:
  engine:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gemini_engine
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:serve --host 0.0.0.0 --port 8000 --reload  # 추가
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - sec-network
    depends_on:
      - target-app

  target-app:
    build: 
      context: ./target_app_mock
      dockerfile: Dockerfile
    container_name: gemini_target
    ports:
      - "3000:3000"
    networks:
      - sec-network

networks:
  sec-network:
    driver: bridge